spring.application.name=tasks
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=system
spring.datasource.password=eos
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
jwt.secret=TXlTZWNyZXRLZXkyMDI2Rm9ySnd0U2lnbmluZ1Rhc2tzQXBwISE=
jwt.expiration.ms=3600000