-- CREATE
CREATE USER task IDENTIFIED BY 'task';

CREATE TABLE STATUS_TYPES (
    status_type_id VARCHAR2(255),
    status_name VARCHAR2(500),
    creation_date DATE DEFAULT SYSDATE NOT NULL,
    created_by VARCHAR2(50) DEFAULT USER NOT NULL,
    last_update_date DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by VARCHAR2(50) DEFAULT USER NOT NULL,
    created_by_fullname VARCHAR2(300),
    CONSTRAINT status_types_pk PRIMARY KEY (status_type_id)
);

SELECT * FROM STATUS_TYPES;

CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(500),
    birth_date DATE,
    is_internal NUMBER(1) DEFAULT 1,
    creation_date DATE DEFAULT SYSDATE NOT NULL,
    created_by VARCHAR2(50) DEFAULT USER NOT NULL,
    last_update_date DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by VARCHAR2(50) DEFAULT USER NOT NULL,
    created_by_fullname VARCHAR2(300),
    CONSTRAINT users_pk PRIMARY KEY (user_id)
);

SELECT * FROM USERS;

CREATE TABLE TASKS (
    task_id NUMBER(13) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(500) NOT NULL,
    status_type_id VARCHAR2(255),
    user_id NUMBER(13),
    due_date DATE,
    created_by VARCHAR2(50) DEFAULT USER,
    CONSTRAINT tasks_pk PRIMARY KEY (task_id),
    CONSTRAINT tasks_statuses_fk FOREIGN KEY (status_type_id) REFERENCES status_types (status_type_id),
    CONSTRAINT tasks_users_fk FOREIGN KEY (user_id) REFERENCES users (user_id)
);

SELECT * FROM TASKS;

-- ALTER
ALTER TABLE TASKS RENAME COLUMN name TO task_name;

ALTER TABLE TASKS ADD (
	creation_date DATE DEFAULT SYSDATE NOT NULL,
    last_update_date DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by VARCHAR2(50) DEFAULT USER NOT NULL,
    created_by_fullname VARCHAR2(300)
);

-- INSERT
INSERT INTO STATUS_TYPES (status_type_id, status_name, created_by, created_by_fullname)
VALUES (SYS_GUID(), 'Pending', 'Andrei', 'SUMMER_SCHOOL');

INSERT INTO STATUS_TYPES (status_type_id, status_name, created_by, created_by_fullname)
VALUES (SYS_GUID(), 'In Progress', 'Andrei', 'SUMMER_SCHOOL');

INSERT INTO STATUS_TYPES (status_type_id, status_name, created_by, created_by_fullname)
VALUES (SYS_GUID(), 'Cancelled', 'Andrei', 'SUMMER_SCHOOL');

INSERT INTO USERS (username, birth_date, is_internal, created_by, created_by_fullname)
VALUES ('Ioana', TO_DATE('1998-04-12', 'YYYY-MM-DD'), 1, 'Ioana', 'SUMMER_SCHOOL');

INSERT INTO USERS (username, birth_date, is_internal, created_by, created_by_fullname)
VALUES ('Alice', TO_DATE('1995-09-23', 'YYYY-MM-DD'), 0, 'Alice', 'SUMMER_SCHOOL');

INSERT INTO USERS (username, birth_date, is_internal, created_by, created_by_fullname)
VALUES ('Catalin', TO_DATE('1990-01-15', 'YYYY-MM-DD'), 1, 'Catalin', 'SUMMER_SCHOOL');

INSERT INTO tasks (task_name, status_type_id, user_id, due_date, created_by, creation_date, created_by_fullname) 
VALUES ('Revizuirea documentației', (SELECT status_type_id FROM status_types WHERE status_name = 'Pending'), 1, TO_DATE('2023-10-05', 'YYYY-MM-DD'), 'Ioana', SYSDATE, 'SUMMER_SCHOOL');​

INSERT INTO tasks (task_name, status_type_id, user_id, due_date, created_by, created_by_fullname) 
VALUES ('Testarea aplicației', (SELECT status_type_id FROM status_types WHERE status_name = 'In Progress'), 2, SYSDATE, 'Alice', 'SUMMER_SCHOOL');

INSERT INTO tasks (task_name, status_type_id, user_id, due_date, created_by, creation_date, created_by_fullname) 
VALUES ('Finalizarea raportului de vânzări', (SELECT status_type_id FROM status_types WHERE status_name = 'Cancelled'), 3, TO_DATE('2025-08-05', 'YYYY-MM-DD'), 'Catalin', SYSDATE, 'SUMMER_SCHOOL');

-- SELECT
SELECT * FROM TASKS WHERE TRUNC(CREATION_DATE) = TRUNC(SYSDATE);

-- UPDATE
UPDATE tasks SET due_date = TO_DATE('2023-10-05', 'YYYY-MM-DD') WHERE task_id = 1;
UPDATE tasks SET due_date = TO_DATE('2023-10-05', 'YYYY-MM-DD') WHERE CREATED_BY = 'Ioana';

-- DELETE
DELETE FROM tasks WHERE task_id = 1;

-- VIEW
CREATE OR REPLACE VIEW active_tasks_v AS
SELECT task_id, task_name, due_date
FROM TASKS T
JOIN STATUS_TYPES S ON T.status_type_id = S.status_type_id
WHERE S.status_name IN ('In Progress', 'Not Started');

SELECT * FROM active_tasks_v;

-- FUNCTIE
CREATE OR REPLACE FUNCTION GET_task_status(P_task_id NUMBER)
RETURN VARCHAR2 AS
    V_task_status_output VARCHAR2(255);
BEGIN
    SELECT ST.status_name
    INTO V_task_status_output
    FROM STATUS_TYPES ST
    JOIN TASKS T ON ST.status_type_id = T.status_type_id
    WHERE T.task_id = P_task_id;

    RETURN V_task_status_output;
END;

SELECT GET_task_status(2) FROM DUAL;


-- TEMA

-- 1. De inserat 2 rânduri în fiecare tabelă.

-- STATUS_TYPES
INSERT INTO STATUS_TYPES (status_type_id, status_name, created_by, created_by_fullname)
VALUES (SYS_GUID(), 'Not Started', 'Andrei', 'SUMMER_SCHOOL');

INSERT INTO STATUS_TYPES (status_type_id, status_name, created_by, created_by_fullname)
VALUES (SYS_GUID(), 'Completed', 'Andrei', 'SUMMER_SCHOOL');

SELECT * FROM STATUS_TYPES;

-- USERS
INSERT INTO USERS (username, birth_date, is_internal, created_by, created_by_fullname)
VALUES ('Mihai', TO_DATE('1985-03-20', 'YYYY-MM-DD'), 1, 'Andrei', 'SUMMER_SCHOOL');

INSERT INTO USERS (username, birth_date, is_internal, created_by, created_by_fullname)
VALUES ('Elena', TO_DATE('2000-11-05', 'YYYY-MM-DD'), 0, 'Andrei', 'SUMMER_SCHOOL');

SELECT * FROM USERS;

-- TASKS
INSERT INTO tasks (task_name, status_type_id, user_id, due_date, created_by, creation_date, created_by_fullname)
VALUES ('Actualizare documentatie API', 
        (SELECT status_type_id FROM status_types WHERE status_name = 'Pending'), 
        (SELECT user_id FROM users WHERE username = 'Ioana'), 
        TO_DATE('05-08-2025', 'DD-MM-YYYY'), 'Andrei', SYSDATE, 'SUMMER_SCHOOL');

INSERT INTO tasks (task_name, status_type_id, user_id, due_date, created_by, creation_date, created_by_fullname)
VALUES ('Optimizare interogari SQL', 
        (SELECT status_type_id FROM status_types WHERE status_name = 'In Progress'), 
        (SELECT user_id FROM users WHERE username = 'Mihai'), 
        SYSDATE, 'Andrei', SYSDATE, 'SUMMER_SCHOOL');

SELECT * FROM TASKS;

-- 2. De creat interogări care să returneze:

-- 2.1 Toate task-urile care sunt în status ‘Pending’ si au due_date = ‘05-08 2025’.
SELECT * 
FROM TASKS t
WHERE t.status_type_id = (
    SELECT status_type_id FROM STATUS_TYPES WHERE status_name = 'Pending'
)
AND t.due_date = TO_DATE('05-08-2025', 'DD-MM-YYYY');

-- 2.2 Toți userii care au task-uri în status ‘In Progress’ și au vârsta mai mare de 30 de ani.
SELECT DISTINCT u.*
FROM USERS u
JOIN TASKS t ON u.user_id = t.user_id
JOIN STATUS_TYPES st ON t.status_type_id = st.status_type_id
WHERE st.status_name = 'In Progress'
AND TRUNC(MONTHS_BETWEEN(SYSDATE, u.birth_date) / 12) > 30;

-- 3. Documentare despre proceduri + creare procedurã care sa steargã task-urile care sunt în status ‘Cancelled’ si au due_date mai veche de 3 zile. 
CREATE OR REPLACE PROCEDURE delete_cancelled_tasks AS
BEGIN
    DELETE FROM TASKS
    WHERE status_type_id = (
        SELECT status_type_id 
        FROM STATUS_TYPES 
        WHERE status_name = 'Cancelled'
    )
    AND SYSDATE - due_date >= 3;

    COMMIT;
END;

BEGIN
    delete_cancelled_tasks;
END;

SELECT * FROM TASKS;